version: 2.1
jobs:
  build:
    docker:
      - image: gocv/opencv:4.5.5
    working_directory: /usr/local/go/src/github.com/hybridgroup/gocv
    environment:
        DISPLAY: 99.0
        GOCV_CAFFE_TEST_FILES: "/usr/local/go/src/github.com/hybridgroup/gocv/testdata"
        GOCV_TENSORFLOW_TEST_FILES: "/usr/local/go/src/github.com/hybridgroup/gocv/testdata"
        NO_GOCV_ONNX_TEST_FILES: "/usr/local/go/src/github.com/hybridgroup/gocv/testdata"
        OPENCV_ENABLE_NONFREE: ON
    steps:
      - checkout
      - run:
          name: Check Go version
          command: go version
      - run:
          name: "Enforce Go Formatted Code"
          command: "test -z $(gofmt -l .) || gofmt -d ."
      - run:
          name: Install dependencies
          command: |
            apt-get update -yqq && apt-get install xvfb unzip -y
      - run:
          name: "Install Caffe test model"
          command: |
            mkdir -p testdata
            curl -sL https://raw.githubusercontent.com/opencv/opencv_extra/master/testdata/dnn/bvlc_googlenet.prototxt > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/bvlc_googlenet.prototxt
            curl -sL http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/bvlc_googlenet.caffemodel
            curl -sL https://raw.githubusercontent.com/WeChatCV/opencv_3rdparty/wechat_qrcode/detect.caffemodel > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/detect.caffemodel
            curl -sL https://raw.githubusercontent.com/WeChatCV/opencv_3rdparty/wechat_qrcode/detect.prototxt > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/detect.prototxt
            curl -sL https://raw.githubusercontent.com/WeChatCV/opencv_3rdparty/wechat_qrcode/sr.caffemodel > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/sr.caffemodel
            curl -sL https://raw.githubusercontent.com/WeChatCV/opencv_3rdparty/wechat_qrcode/sr.prototxt > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/sr.prototxt
      - run:
          name: "Install Tensorflow test model"
          command: |
            mkdir -p testdata
            curl -sL https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/inception5h.zip
            unzip -o /usr/local/go/src/github.com/hybridgroup/gocv/testdata/inception5h.zip tensorflow_inception_graph.pb -d /usr/local/go/src/github.com/hybridgroup/gocv/testdata
      - run:
          name: "Install ONNX test model"
          command: |
            mkdir -p testdata
            curl -sL https://github.com/onnx/models/blob/master/vision/classification/inception_and_googlenet/googlenet/model/googlenet-9.onnx\?raw\=true > /usr/local/go/src/github.com/hybridgroup/gocv/testdata/googlenet-9.onnx
      - run:
          name: Run main tests
          command: | 
            xvfb-run -a --error-file /var/log/xvfb_error.log --server-args="-screen 0 1024x768x24 +extension RANDR" go test -v -coverprofile=/tmp/coverage.out -count=1 -tags matprofile .
      - run:
          name: Run contrib tests
          command: | 
            xvfb-run -a --error-file /var/log/xvfb_error.log --server-args="-screen 0 1024x768x24 +extension RANDR" go test -v -coverprofile=/tmp/contrib.out -count=1 -tags matprofile ./contrib
      - run:
          name: Code coverage
          command: | 
            go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
            go tool cover -html=/tmp/contrib.out -o /tmp/contrib.html
      - store_artifacts:
          path: /tmp/coverage.html
          destination: test-coverage.html
      - store_artifacts:
          path: /tmp/contrib.html
          destination: test-coverage-contrib.html
